// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVGz0H_sApJLg77kwpAN_9_O4xZIxjjA',
    appId: '1:14836166006:web:a66d4df9b0c050042b5e57',
    messagingSenderId: '14836166006',
    projectId: 'tunes01',
    authDomain: 'tunes01.firebaseapp.com',
    storageBucket: 'tunes01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXEZQCavNQMM7d58yQHIroCjrO5EKHkY',
    appId: '1:14836166006:android:ad06fbb11f70e4f12b5e57',
    messagingSenderId: '14836166006',
    projectId: 'tunes01',
    storageBucket: 'tunes01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBU4LL86rHPa_60vQnl6UsoN58BhwPXU',
    appId: '1:14836166006:ios:bb417a74e5dbac6a2b5e57',
    messagingSenderId: '14836166006',
    projectId: 'tunes01',
    storageBucket: 'tunes01.firebasestorage.app',
    iosBundleId: 'com.example.tunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBU4LL86rHPa_60vQnl6UsoN58BhwPXU',
    appId: '1:14836166006:ios:bb417a74e5dbac6a2b5e57',
    messagingSenderId: '14836166006',
    projectId: 'tunes01',
    storageBucket: 'tunes01.firebasestorage.app',
    iosBundleId: 'com.example.tunes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeVGz0H_sApJLg77kwpAN_9_O4xZIxjjA',
    appId: '1:14836166006:web:afe2bc5b6ea55bab2b5e57',
    messagingSenderId: '14836166006',
    projectId: 'tunes01',
    authDomain: 'tunes01.firebaseapp.com',
    storageBucket: 'tunes01.firebasestorage.app',
  );
}
